FROM sider/devon_rex_npm:2.2.0

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.npm.erb' %>

COPY images/jshint/sider_jshintignore images/jshint/sider_jshintrc $RUNNER_USER_HOME/

<%= render_erb 'images/Dockerfile.end.erb' %>
