FROM sider/devon_rex_dotnet:master
ENV FXCOP_VERSION=2.9.8

<%= render_erb 'images/Dockerfile.base.erb' %>

# cache target analyzer
USER $RUNNER_USER
RUN cd && \
    mkdir dummy_project && \
    cd dummy_project && \
    dotnet new console && \
    dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers --version ${FXCOP_VERSION} && \
    cd && \
    rm -rf dummy_project

<%= render_erb 'images/Dockerfile.end.erb' %>
