FROM sider/devon_rex_dotnet:2.14.0

<%= render_erb 'images/Dockerfile.base.erb' %>

# cache target analyzer
USER $RUNNER_USER
RUN cd && \
    mkdir dummy_project && \
    cd dummy_project && \
    dotnet new console && \
    dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers --version 2.9.8 && \
    cd && \
    rm -rf dummy_project

<%= render_erb 'images/Dockerfile.end.erb' %>
