FROM sider/devon_rex_java:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

ENV JAVASEE_VERSION 0.1.1
USER root
RUN curl -O -L https://github.com/sider/JavaSee/releases/download/${JAVASEE_VERSION}/JavaSee-bin-${JAVASEE_VERSION}.zip \
  && unzip JavaSee-bin-${JAVASEE_VERSION}.zip \
  && mv JavaSee-${JAVASEE_VERSION} /usr/local/JavaSee \
  && ln -s /usr/local/JavaSee/bin/javasee /usr/local/bin/javasee \
  && rm -rf *.zip

USER $RUNNER_USER

ENTRYPOINT ["node_harness", "--analyzer=javasee"]
