FROM sider/devon_rex_java:2.18.0

ARG JAVASEE_VERSION=0.1.3

RUN cd /tmp && \
    curl -fsSLO --compressed https://github.com/sider/JavaSee/releases/download/${JAVASEE_VERSION}/JavaSee-bin-${JAVASEE_VERSION}.zip && \
    unzip JavaSee-bin-${JAVASEE_VERSION}.zip && \
    mkdir ${RUNNER_USER_HOME}/JavaSee && \
    cp -rv JavaSee-${JAVASEE_VERSION}/bin ${RUNNER_USER_HOME}/JavaSee/bin && \
    cp -rv JavaSee-${JAVASEE_VERSION}/lib ${RUNNER_USER_HOME}/JavaSee/lib && \
    ln -sv ${RUNNER_USER_HOME}/JavaSee/bin/javasee ${RUNNER_USER_HOME}/bin/javasee && \
    rm JavaSee-bin-${JAVASEE_VERSION}.zip && \
    rm -r JavaSee-${JAVASEE_VERSION} && \
    javasee version

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
