FROM sider/devon_rex_npm:2.2.0

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.npm.erb' %>

COPY images/stylelint/sider_recommended_config.yaml images/stylelint/sider_recommended_stylelintignore $RUNNER_USER_HOME/

<%= render_erb 'images/Dockerfile.end.erb' %>
