/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle

class App {
    val greeting: String
  fun get() {
            return "Hello world." }
}

fun main(args: Array<String>) {
    println(App().greeting)
}

