module Runners
  class Workspace::Git < Workspace
    class Error < SystemError
    end

    class FetchFailed < Error
    end

    class CheckoutFailed < Error
    end

    class BlameFailed < Error
    end

    private

    def git_source: () -> Options::GitSource

    def try_count: () -> Integer

    def sleep_lambda: () -> ^(Numeric) -> Numeric

    def remote_url: () -> String

    def git_setup: () -> void

    def git_clone: () -> void

    def git_fetch: (Array[String]) -> void

    def git_checkout: () -> void

    def git_sparse_checkout_set: (*String) -> void
  end
end
