module Runners
  class Workspace::Git < Workspace
    class Error < SystemError
    end

    class FetchFailed < Error
    end

    class CheckoutFailed < Error
    end

    class BlameFailed < Error
    end

    private

    def git_source: () -> Options::GitSource

    def try_count: () -> Integer

    def sleep_lambda: () -> ^(Integer) -> Numeric

    def remote_url: () -> String

    def git_fetch_args: () -> Array[String]
  end
end
