FROM sider/devon_rex_ruby:2.40.4

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.ruby.erb' %>

COPY --chown=<%= chown %> images/rubocop/default_rubocop.yml ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
