module Runners
  module Nodejs
    class Constraint
      def initialize: (String, *String) -> void

      def satisfied_by?: (Dependency) -> bool

      def unsatisfied_by?: (Dependency) -> bool
    end
  end
end
