FROM sider/devon_rex_ruby:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

# Install the default version for caching
RUN gem install brakeman -v 4.3.1

ENTRYPOINT ["runners", "--analyzer=brakeman"]
