FROM sider/devon_rex_ruby:2.1.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

# Install the default version for caching
RUN gem install brakeman -v 4.3.1

ENTRYPOINT ["node_harness", "--analyzer=brakeman"]
