FROM sider/devon_rex_python:master

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.python.erb' %>

COPY images/flake8/sider_config.ini $RUNNER_USER_HOME/.config/flake8
COPY images/flake8/ignored-config.ini $RUNNER_USER_HOME/.config/ignored-config.ini

<%= render_erb 'images/Dockerfile.end.erb' %>
