FROM sider/devon_rex_go:2.12.0

ARG LINT_TOOL_VERSION="1.23.6"

USER root
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v${LINT_TOOL_VERSION}

USER $RUNNER_USER
RUN golangci-lint --version

<%= render_erb 'images/Dockerfile.base.erb' %>
COPY --chown=<%= chown %> images/golangci_lint/sider_golangci.yml ${RUNNER_USER_HOME}/
<%= render_erb 'images/Dockerfile.end.erb' %>
