FROM golangci/golangci-lint:v1.33.0 as golangci-lint

FROM sider/devon_rex_go:master

COPY --chown=<%= chown %> --from=golangci-lint /usr/bin/golangci-lint ${RUNNER_USER_HOME}/bin/

<%= render_erb 'images/Dockerfile.base.erb' %>

COPY --chown=<%= chown %> images/golangci_lint/sider_golangci.yml ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
