FROM sider/devon_rex_base:2.27.1

ARG MISSPELL_VERSION=0.3.4

RUN curl -fsSL https://git.io/misspell | bash -s -- -b "${RUNNER_USER_HOME}/bin" "v${MISSPELL_VERSION}" && \
    misspell -v

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
