FROM sider/devon_rex_ruby:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

COPY images/reek/v5.reek.yml $RUNNER_USER_HOME/.reek.yml
COPY images/reek/v4.reek.yml $RUNNER_USER_HOME/config.reek
RUN gem install reek -v 5.4.0

ENTRYPOINT ["node_harness", "--analyzer=reek"]
