module Runners
  class Processor::Brakeman < Processor
    include Ruby

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    GEM_NAME: String
    CONSTRAINTS: Ruby::constraints
  end
end
