module Runners
  class Processor::Checkstyle < Processor
    include Java

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_CONFIG_FILE: String
    OFFICIAL_RULE_NAMESPACE: String

    private

    def checkstyle_args: () -> Array[String]

    def construct_result: (REXML::Element) { (Issue) -> void } -> void

    def normalize_id: (String) -> String

    def build_links: (String) -> Array[String]

    def config_file: () -> String?

    def excluded_directories: () -> Array[Hash[Symbol, String?]]
  end
end
