module Runners
  class Processor::Coffeelint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    CONSTRAINTS: Nodejs::constraints

    private

    def config_file: () -> Array[String]
  end
end
