module Runners
  class Processor::Cppcheck < Processor
    include CPlusPlus

    class NoTargetFiles < SystemError
    end

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_SUPPRESSIONS_PATH: String
    DEFAULT_TARGET: String
    DEFAULT_IGNORE: Array[String]

    private

    def target: () -> Array[String]

    def ignore: () -> Array[String]

    def addon: () -> Array[String]

    def enable: () -> Array[String]

    def std: () -> Array[String]

    def project: () -> Array[String]

    def language: () -> Array[String]

    def suppressions_list: () -> Array[String]

    def jobs: () -> Array[String]

    def step_analyzer: (*String) -> result

    def parse_result: (Nokogiri::XML::Document) { (Issue) -> void } -> void
  end
end
