module Runners
  class Processor::Cpplint < Processor
    include RecommendedConfig

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    CONFIG_FILE_NAME: String

    private

    def analyzer_options: () -> Array[String]

    def parse_result: (Nokogiri::XML::Document) -> Array[Issue]
  end
end
