module Runners
  class Processor::Cpplint < Processor
    include RecommendedConfig

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    DEFAULT_TARGET: String
    CONFIG_FILE_NAME: String

    private

    def analyzer_options: () -> Array[String]

    def parse_result: (REXML::Element) -> Array[Issue]
  end
end
