module Runners
  class Processor::Detekt < Processor
    include Java
    include Kotlin

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    private

    def parse_output: () -> Array[Issue]
  end
end
