module Runners
  class Processor::Eslint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    CONSTRAINTS: Nodejs::constraints
    CUSTOM_FORMATTER: String
    DEFAULT_ESLINT_CONFIG: String
    DEFAULT_TARGET: String

    private

    def target: () -> Array[String]

    def eslint_config: () -> String?

    def ext: () -> Array[String]

    def ignore_path: () -> Array[String]

    def ignore_pattern: () -> Array[String]

    def no_ignore: () -> Array[String]

    def global: () -> Array[String]

    def quiet: () -> Array[String]

    def normalize_severity: (Integer) -> String

    def parse_result: (Array[untyped]) { (Issue) -> void } -> void

    def run_analyzer: (?config: String?) -> result

    def no_linting_files?: (String) -> bool

    def no_eslint_config?: (String) -> bool
  end
end
