module Runners
  class Processor::Flake8 < Processor
    include Python

    Schema: untyped

    # Output example:
    #
    # E999:::app1/views.py:::6:::12:::IndentationError: unexpected indent
    #
    # `:::` is a separater
    #
    OUTPUT_FORMAT: untyped

    OUTPUT_PATTERN: untyped

    DEFAULT_TARGET: untyped

    def setup: () { () -> untyped } -> untyped

    def analyze: (untyped changes) -> untyped

    def prepare_config: () -> untyped

    def prepare_plugins: () -> untyped

    def ignored_config_path: () -> untyped

    def parse_result: (untyped output) { (untyped) -> untyped } -> untyped

    def run_analyzer: () -> untyped
  end
end
