module Runners
  class Processor::Flake8 < Processor
    include Python

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_CONFIG_PATH: String
    DEFAULT_IGNORED_CONFIG_PATH: String

    private

    def prepare_config: () -> void

    def parse_result: (String) -> Array[Issue]
  end
end
