module Runners
  class Processor::FxCop < Processor
    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    private

    def construct_result: (Array[Hash[Symbol, untyped]]) { (Issue) -> void } -> void
  end
end
