module Runners
  class Processor::GolangCiLint < Processor
    include Go

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_CONFIG_FILE: String
    SUPPORTED_CONFIG_FILES: Array[String]

    private

    def analyzer_options: () -> Array[String]

    def path_to_config: () -> String?

    def analysis_targets: () -> Array[String]

    def parse_result: (String) { (Issue) -> void } -> void
  end
end
