module Runners
  class Processor::Hadolint < Processor
    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_TARGET_EXCLUDED: String

    private

    def analyzer_options: () -> Array[String]

    def analysis_targets: () -> Array[String]

    def parse_result: (String) -> Array[Issue]

    def link_to_wiki: (String) -> Array[String]
  end
end
