module Runners
  class Processor::HamlLint < Processor
    include Ruby
    include RuboCopUtils

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]
    DEFAULT_GEMS: Array[String]
    GEM_NAME: String
    REQUIRED_GEM_NAMES: Array[String]
    CONSTRAINTS: Ruby::constraints
    DEFAULT_TARGET: String

    private

    def target: () -> Array[String]

    def include_linter: () -> Array[String]

    def exclude_linter: () -> Array[String]

    def exclude: () -> Array[String]

    def haml_lint_config: () -> Array[String]

    def config_parallel: () -> Array[String]

    def parse_result: (String) -> Array[Issue]

    def extract_cop_name: (String) -> String?

    def build_links: (String?, String?) -> Array[String]

    def add_rubocop_warnings_if_exists: (String) -> void
  end
end
