module Runners
  class Processor::Javasee < Processor
    include Java

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def rule: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_CONFIG_FILE: String

    private

    def construct_result: (String) { (Issue) -> void } -> void
  end
end
