module Runners
  class Processor::Jshint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_CONFIG_FILE: String
    DEFAULT_IGNORE_FILE: String

    private

    def prepare_config: () -> void

    def jshintrc_exist?: () -> bool

    def config_path: () -> String?

    def parse_result: (String) -> Array[Issue]
  end
end
