module Runners
  class Processor::Ktlint < Processor
    include Java
    include Kotlin

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    private

    def parse_json_output: (String) -> Array[Issue]
  end
end
