module Runners
  class Processor::Ktlint < Processor
    include Java

    include Kotlin

    Schema: untyped

    def setup: () { () -> untyped } -> untyped

    def analyze: (untyped changes) -> untyped

    def parse_json_output: (untyped output) { (untyped) -> untyped } -> untyped
  end
end
