module Runners
  class Processor::LanguageTool < Processor
    include Java

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_EXT: String
    DEFAULT_EXCLUDE: String
    DEFAULT_LANGUAGE: String
    DEFAULT_ENCODING: String

    private

    def delete_files_except_targets: () -> void

    def config_target: () -> String

    def config_ext: () -> Array[String]

    def config_exclude: () -> Array[String]

    def config_language: () -> String

    def config_encoding: () -> String

    def cli_comma_separated_list: (Symbol, String) -> Array[String]

    def cli_disable: () -> Array[String]

    def cli_enable: () -> Array[String]

    def cli_enabledonly: () -> Array[String]

    def cli_disablecategories: () -> Array[String]

    def cli_enablecategories: () -> Array[String]

    def cli_args: () -> Array[String]

    def run_analyzer: () -> result

    def parse_output: (String) { (String, Hash[Symbol, untyped]) -> void } -> void

    def offset_ranges_per_line: (Array[String]) -> Array[Range[Integer]]
  end
end
