module Runners
  class Processor::MetricsCodeClone < Processor

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    def initialize: (**untyped) -> void

    private

    def construct_file_issue: (Array[Issue], Pathname) -> Issue
  end
end
