module Runners
  class Processor::MetricsComplexity < Processor
    include Python

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    private

    def construct_file_issues: (REXML::Element) -> Array[Issue]
  end
end
