module Runners
  class Processor::Phinder < Processor
    include PHP

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    DEFAULT_RULE_FILE: String

    private

    def test_phinder_config: () -> void

    def run_phinder: () -> result
  end
end
