module Runners
  class Processor::Phpmd < Processor
    include PHP

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    DEFAULT_TARGET: String
    DEFAULT_CONFIG_FILE: String

    private

    def target_files: () -> Array[String]

    def rule: () -> String

    def target_dirs: () -> String

    def minimumpriority: () -> Array[String]

    def suffixes: () -> Array[String]

    def exclude: () -> Array[String]

    def strict: () -> Array[String]

    def run_analyzer: (Changes) -> result
  end
end
