module Runners
  class Processor::Phpmd < Processor
    include PHP

    Schema: untyped

    DEFAULT_TARGET: untyped

    DEFAULT_CONFIG_FILE: untyped

    def setup: () { () -> untyped } -> untyped

    def analyze: (untyped changes) -> untyped

    def target_files: () -> untyped

    def rule: () -> untyped

    def target_dirs: () -> untyped

    def minimumpriority: () -> untyped

    def suffixes: () -> untyped

    def exclude: () -> untyped

    def strict: () -> untyped

    def run_analyzer: (untyped changes) -> untyped
  end
end
