module Runners
  class Processor::PmdJava < Processor
    include Java

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    DEFAULT_RULESET: String
    DEFAULT_DIR: String

    private

    def cli_args: () -> Array[String]

    def construct_result: () { (Issue) -> void } -> void
  end
end
