module Runners
  class Processor::PmdJava < Processor
    include Java

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    DEFAULT_RULESET: String
    DEFAULT_DIR: String

    private

    def cli_args: () -> Array[String]

    def construct_result: (REXML::Element) { (Issue) -> void } -> void

    def rulesets: () -> Array[String]

    def dir: () -> String

    def encoding: () -> Array[String]

    def min_priority: () -> Array[String]
  end
end
