module Runners
  class Processor::Querly < Processor
    include Ruby

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def rule: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]
    GEM_NAME: String
    CONSTRAINTS: Ruby::constraints
    CONFIG_FILE: String
    CONFIG_FILES_GLOB: String

    private

    def config_file: () -> String?

    def option_config_file: () -> Array[String]

    def default_config_file: () -> String?

    def querly_test: () -> void
  end
end
