module Runners
  class Processor::RailsBestPractices < Processor
    include Ruby

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]
    GEM_NAME: String
    CONSTRAINTS: Ruby::constraints

    private

    def option_vendor: () -> Array[String]

    def option_spec: () -> Array[String]

    def option_test: () -> Array[String]

    def option_features: () -> Array[String]

    def option_exclude: () -> Array[String]

    def option_only: () -> Array[String]

    def option_config: () -> Array[String]

    def prepare_config: () -> void

    def run_analyzer: () -> result
  end
end
