module Runners
  class Processor::Reek < Processor
    include Ruby

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    GEM_NAME: String
    CONSTRAINTS: Ruby::constraints
    DEFAULT_TARGET: String

    private

    def analysis_targets: () -> Array[String]

    def cli_args: () -> Array[String]

    def v4?: () -> bool

    def raise_warnings: (String) -> void
  end
end
