module Runners
  class Processor::RemarkLint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    CONSTRAINTS: Nodejs::constraints
    DEFAULT_TARGET: String
    DEFAULT_PRESET: String

    private

    def analysis_target: () -> Array[String]

    def option_ext: () -> Array[String]

    def option_rc_path: () -> Array[String]

    def option_ignore_path: () -> Array[String]

    def option_use: () -> Array[String]

    def no_rc_files?: () -> bool

    def no_config_in_package_json?: () -> bool

    def use_default_preset?: () -> bool

    def default_preset: () -> Array[String]

    def cli_options: () -> Array[String]

    def parse_result: (String) -> [Array[Issue], Array[String]]
  end
end
