module Runners
  class Processor::RuboCop < Processor
    include Ruby

    Schema: untyped

    OFFICIAL_RUBOCOP_PLUGINS: Array[Ruby::GemInstaller::Spec]

    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]

    CONSTRAINTS: Hash[String, Array[String]]

    DEFAULT_CONFIG_FILE: String

    private

    def rails_option: () -> String?

    def config_file: () -> String?

    def safe: () -> String?

    def setup_default_config: () -> bool

    def check_rubocop_yml_warning: (String) -> void

    def run_analyzer: () -> untyped

    def extract_links: (String) -> Array[String]

    def build_cop_links: (String) -> Array[String]

    def department_to_gem_name: () -> Hash[String, String]

    def normalize_message: (String, Array[String], String) -> String

    def rails_cops_removed?: () -> bool

    def cache_root: () -> String?
  end
end
