module Runners
  class Processor::RuboCop < Processor
    include Ruby

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    OFFICIAL_RUBOCOP_PLUGINS: Array[Ruby::GemInstaller::Spec]
    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]
    GEM_NAME: String
    CONSTRAINTS: Hash[String, Array[String]]
    DEFAULT_CONFIG_FILE: String

    private

    def rails_option: () -> Array[String]

    def config_file: () -> Array[String]

    def safe: () -> Array[String]

    def setup_default_config: () -> bool

    def check_rubocop_yml_warning: (String) -> void

    def extract_links: (String) -> Array[String]

    def build_cop_links: (String) -> Array[String]

    def department_to_gem_name: () -> Hash[String, String]

    def department_to_gem_name_ext: () -> Hash[String, String]

    def gem_info: (String) -> String

    def normalize_message: (String, Array[String], String) -> String

    def rails_cops_removed?: () -> bool

    def cache_root: () -> Array[String]
  end
end
