module Runners
  class Processor::ScssLint < Processor
    include Ruby

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    EXIT_CODE_FILES_NOT_EXIST: Integer

    private

    def scss_lint_config: () -> Array[String]

    def parse_result: (String) -> Array[Issue]
  end
end
