module Runners
  class Processor::SecretScan < Processor
    class SchemaClass < StrongJSON
      def rule: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    private

    def rule_file: () -> Pathname
  end
end
