module Runners
  class Processor::ShellCheck < Processor
    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    type target = String | Hash[Symbol, bool]

    DEFAULT_TARGET: Array[target]
    SHELL_SCRIPT_SHEBANG_PATTERN: Regexp

    private

    def find_files_with_shebang: () -> Array[String]

    def analyzed_files: () -> Array[String]

    def option_values: (Symbol, String) -> String

    def analyzer_options: () -> Array[String]

    def parse_result: (String) { (Issue) -> void } -> void
  end
end
