module Runners
  class Processor::SlimLint < Processor
    include Ruby
    include RuboCopUtils

    class SchemaClass < StrongJSON
      include Schema::ConfigTypes

      def config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    SCHEMA: SchemaClass

    GEM_NAME: String
    REQUIRED_GEM_NAMES: Array[String]
    CONSTRAINTS: Ruby::constraints
    DEFAULT_TARGET: String
    DEFAULT_CONFIG_FILE: String
    MISSING_ID: String
    OPTIONAL_GEMS: Array[Ruby::GemInstaller::Spec]

    private

    def setup_slim_lint_config: () -> void

    def parse_result: (String) -> Array[Issue]

    def build_id: (String?, String) -> String

    def build_links: (String?) -> Array[String]
  end
end
