module Runners
  class Processor::Stylelint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    CONSTRAINTS: Nodejs::constraints
    DEFAULT_TARGET_FILES: String
    DEFAULT_GLOB: String
    DEFAULT_CONFIG_FILE: String
    DEFAULT_CONFIG_FILE_OLD: String
    DEFAULT_IGNORE_FILE: String

    private

    def glob: () -> String

    def stylelint_config: () -> Array[String]

    def syntax: () -> Array[String]

    def ignore_path: () -> Array[String]

    def ignore_disables: () -> Array[String]

    def report_needless_disables: () -> Array[String]

    def quiet: () -> Array[String]

    def parse_result: (String) -> Array[Issue]

    def normalize_message: (String, String) -> String

    def rule_doc_urls: () -> Hash[String, String]

    def prepare_config_file: () -> void

    def prepare_ignore_file: () -> void

    def config_file_path: () -> Pathname?

    def check_warning: (Array[Hash[Symbol, String]]) -> void
  end
end
