module Runners
  class Processor::Tslint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    CONSTRAINTS: Nodejs::constraints
    DEFAULT_TARGET: String

    private

    def target_glob: () -> String

    def tslint_config: () -> Array[String]

    def exclude: () -> Array[String]

    def project: () -> Array[String]

    def rules_dir: () -> Array[String]

    def type_check: () -> Array[String]
  end
end
