module Runners
  class Processor::Tyscan < Processor
    include Nodejs

    # Define schema in sider.yml
    Schema: untyped

    CONSTRAINTS: untyped

    DEFAULT_CONFIG_FILE: untyped

    def setup: () { () -> untyped } -> untyped

    def analyze: (untyped _) -> untyped

    def tyscan_test: () -> untyped

    def tyscan_scan: () -> untyped
  end
end
