module Runners
  class Processor::Tyscan < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[untyped]
      def issue: () -> StrongJSON::Type::Object[untyped]
    end
    Schema: SchemaClass

    CONSTRAINTS: Nodejs::constraints
    DEFAULT_CONFIG_FILE: String

    private

    def tyscan_test: () -> void

    def tyscan_scan: () -> result
  end
end
