module JSONSEQ
end

interface JSONSEQ::_WriteIO
  def write: (String) -> void
  def flush: () -> void
end

class JSONSEQ::Writer
  def initialize: (io: _WriteIO) -> void
  def <<: (untyped) -> void
end
