# TODO: Remove this file after the dependency of ruby-signature in steep is updated.
extension Pathname (Pathname)
  def to_path: () -> String
  def delete: () -> void

  def +: (Pathname | String | _ToStr other) -> Pathname
  alias / +

  def glob: (String | Array[String] pattern, ?Integer flags) -> Array[Pathname]
          | (String | Array[String] pattern, ?Integer flags) { (Pathname) -> untyped } -> nil
end
