FROM sider/devon_rex_ruby:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

RUN gem install querly -v 1.0.0 && \
    gem install slim -v 4.0.1 && \
    gem install haml -v 5.1.2

ENTRYPOINT ["runners", "--analyzer=querly"]
