FROM sider/devon_rex_npm:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

ARG COFFEELINT_VERSION=1.16.0
USER root
RUN npm install -g coffeelint@${COFFEELINT_VERSION}
USER $RUNNER_USER

ENTRYPOINT ["runners", "--analyzer=coffeelint"]
