FROM sider/devon_rex_npm:2.2.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>
<%= ERB.new(File.read('images/Dockerfile.npm.erb')).result %>

ENTRYPOINT ["runners", "--analyzer=coffeelint"]
