FROM sider/devon_rex_go:2.5.0

<%= render_erb 'images/Dockerfile.base.erb' %>

ARG LINT_TOOL_VERSION="3.0.0"

USER root
RUN curl -L https://github.com/alecthomas/gometalinter/releases/download/v${LINT_TOOL_VERSION}/gometalinter-${LINT_TOOL_VERSION}-linux-amd64.tar.gz | \
    tar -xzC . && \
    cd gometalinter-${LINT_TOOL_VERSION}-linux-amd64/ && \
    rm COPYING README.md && \
    mv * /usr/local/bin/ && \
    cd .. && \
    rm -r gometalinter-${LINT_TOOL_VERSION}-linux-amd64/
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.end.erb' %>
