module Runners
  module Ruby
    class LockfileLoader
      class Lockfile
        type spec = GemInstaller::Spec | String

        attr_reader specs: Array[GemInstaller::Spec]

        def initialize: (String?) -> void

        def spec_exists?: (spec) -> bool

        def locked_version: (spec) -> String?

        def locked_version!: (spec) -> String

        def satisfied_by?: (spec, Hash[String, Array[String]]) -> bool

        private

        def find_spec: (spec) -> GemInstaller::Spec?
      end
    end
  end
end
