module Runners
  module Ruby
    class LockfileLoader
      class Lockfile
        type spec = GemInstaller::Spec | String

        def initialize: (String?) -> void

        def empty?: () -> bool

        def spec_exists?: (spec) -> bool

        def locked_version: (spec) -> Gem::Version?

        def locked_version!: (spec) -> Gem::Version

        def satisfied_by?: (spec, constraints) -> bool

        private

        attr_reader specs: Array[Bundler::LazySpecification]

        def find_spec: (spec) -> Bundler::LazySpecification?
      end
    end
  end
end
