FROM sider/devon_rex_php:2.0.3

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

COPY images/phinder/composer.json images/phinder/composer.lock $COMPOSER_HOME/
RUN composer global install

ENTRYPOINT ["node_harness", "--analyzer=phinder"]
