FROM sider/devon_rex_python:2.0.3

# NOTE: The reason using Python image: when setting `MATCHCOMPILER=yes`, Python is used to optimise cppcheck.
#
# See https://github.com/danmar/cppcheck#gnu-make

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

ARG CPPCHECK_VERSION=1.89

USER root
RUN cd /tmp \
  && curl -sSL https://github.com/danmar/cppcheck/archive/${CPPCHECK_VERSION}.tar.gz \
  |  tar -xz \
  && cd cppcheck-${CPPCHECK_VERSION} \
  && make install -s MATCHCOMPILER=yes FILESDIR=/usr/share/cppcheck HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" \
  && rm -rf cppcheck-${CPPCHECK_VERSION}
USER $RUNNER_USER

ENTRYPOINT ["node_harness", "--analyzer=cppcheck"]
