FROM sider/devon_rex_python:2.42.0

# NOTE: The reason using Python image: when setting `MATCHCOMPILER=yes`, Python is used to optimise cppcheck.
#
# See https://github.com/danmar/cppcheck#gnu-make

ARG CPPCHECK_VERSION=2.3

# NOTE: A segmentation fault occurs with the latest version of libz3.
ARG LIBZ3_VERSION=4.4.1-1~deb10u1

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends "libz3-dev=${LIBZ3_VERSION}" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    cd /tmp && \
    curl -sSL --compressed "https://github.com/danmar/cppcheck/archive/${CPPCHECK_VERSION}.tar.gz" | tar -xz && \
    cd "cppcheck-${CPPCHECK_VERSION}" && \
    # NOTE: We cannot use the latest version due to a potential segmentation fault.
    cp -v externals/z3_version_old.h externals/z3_version.h && \
    make install -s \
      MATCHCOMPILER=yes \
      FILESDIR=/usr/share/cppcheck \
      HAVE_RULES=yes \
      USE_Z3=yes \
      CPPFLAGS="-DUSE_Z3 -Wno-deprecated-declarations -Wno-unused-function" && \
    rm -rf "cppcheck-${CPPCHECK_VERSION}"

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
