FROM sider/devon_rex_npm:2.42.5

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.npm.erb' %>

COPY --chown=<%= chown %> images/<%= analyzer %>/sider_recommended_remark_lint.yml ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
