module Runners
  class IO::AwsS3
    BUFFER_SIZE: ::Integer

    def self.stub?: () -> bool

    attr_reader uri: String
    attr_reader bucket_name: String
    attr_reader object_name: String
    attr_reader tempfile: Tempfile
    attr_reader written_items: Integer
    attr_reader client: Aws::S3::Client

    def initialize: (String uri, ?endpoint: String?) -> void

    def write: (*_ToS) -> void

    def flush: () -> void

    def should_flush?: () -> bool

    def flush!: () -> void

    private

    def parse_s3_uri: (String) -> { bucket: String, object: String }

    def flush_to_s3!: () -> void
  end
end
