module Runners
  module Schema
    module ConfigTypes
      include StrongJSON::Types

      def one_or_more_strings?: () -> StrongJSON::Type::Optional[untyped]
      def target: () -> StrongJSON::Type::Optional[untyped]
      def dependency: (**untyped) -> StrongJSON::Type::Object[untyped]
      def dependencies: () -> StrongJSON::Type::Optional[untyped]
      def base: (**untyped) -> StrongJSON::Type::Object[untyped]
      def ruby: (**untyped) -> StrongJSON::Type::Object[untyped]
      def cplusplus: (**untyped) -> StrongJSON::Type::Object[untyped]
      def npm: (**untyped) -> StrongJSON::Type::Object[untyped]
      def java: (**untyped) -> StrongJSON::Type::Object[untyped]
    end

    class ConfigClass < StrongJSON
      def payload: () -> StrongJSON::Type::Object[untyped]
      def register: (name: Symbol, schema: StrongJSON::_Schema[untyped]) -> void
    end
    Config: ConfigClass
  end
end
