module Runners
  module Schema
    class OptionsClass < StrongJSON
      def source: () -> StrongJSON::Type::Object[untyped]
      def payload: () -> StrongJSON::Type::Object[untyped]
    end
    Options: OptionsClass
  end
end
