module Aws
  def self.config: () -> Hash[Symbol, Credentials | String]

  class Credentials
    private

    def initialize: (String, String) -> void
  end

  module S3
    # @see https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html
    class Client
      def initialize: (Hash[Symbol, untyped]) -> void
      def put_object: (bucket: String, key: String, body: String | nil) -> void
    end
  end
end
