module Bugsnag
  def self.notify: (Exception) ?{ (Report) -> void } -> void

  def self.configure: () { (Configuration) -> void } -> void

  class Configuration
    attr_accessor api_key: String
    attr_accessor app_version: String
    attr_accessor release_stage: String

    def add_on_error: (untyped) -> void
  end

  class Report
    attr_accessor severity: "error" | "warning" | "info"

    def add_tab: (Symbol, untyped) -> void
  end
end
