module Kernel
  def Rainbow: (String) -> Rainbow
end

class Rainbow
  def bright: () -> self
  def underline: () -> self
  def green: () -> self
  def red: () -> self
  def aqua: () -> self
  def darkgray: () -> self
end
