FROM sider/devon_rex_base:master

COPY --chown=<%= chown %> images/clang_tidy/packages.list ${RUNNER_USER_HOME}/

USER root
RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    add-apt-repository "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" && \
    apt-get update && \
    grep -v "^\s*#" "${RUNNER_USER_HOME}/packages.list" | xargs apt-get install -qq -y --no-install-recommends && \
    apt-get clean && \
    update-alternatives --install /usr/local/bin/clang-tidy clang-tidy /usr/lib/llvm-10/bin/clang-tidy 20
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
