<%= render_erb 'images/Dockerfile.java.erb' %>
<%= render_erb 'images/Dockerfile.base.erb' %>

COPY --chown=<%= chown %> images/<%= analyzer %>/pmd ${RUNNER_USER_BIN}/
COPY --chown=<%= chown %> images/<%= analyzer %>/default-ruleset.xml ${RUNNER_USER_HOME}/

# NOTE: PMD does not have a CLI option to show its version.
COPY --chown=<%= chown %> images/<%= analyzer %>/ShowPMDVersion.java ${RUNNER_USER_BIN}/
COPY --chown=<%= chown %> images/<%= analyzer %>/show_pmd_version ${RUNNER_USER_BIN}/
RUN cd "${RUNNER_USER_BIN}" && \
    javac ShowPMDVersion.java && \
    rm ShowPMDVersion.java

<%= render_erb 'images/Dockerfile.end.erb' %>
