FROM sider/devon_rex_java:master

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install Gradle
ENV PATH ${RUNNER_USER_HOME}/gradle/bin:${PATH}
ARG GRADLE_VERSION=6.5.1
ARG GRADLE_BINARY_FILE=gradle-${GRADLE_VERSION}-bin.zip
ARG GRADLE_BINARY_URL=https://services.gradle.org/distributions/${GRADLE_BINARY_FILE}
RUN cd "${RUNNER_USER_HOME}" && \
    curl -fsSLO --compressed "${GRADLE_BINARY_URL}" && \
    curl -fsSL  --compressed "${GRADLE_BINARY_URL}.sha256" | \
      xargs -I {} echo "{} *${GRADLE_BINARY_FILE}" | \
      sha256sum --check --strict && \
    unzip -q "${GRADLE_BINARY_FILE}" && \
    mv "gradle-${GRADLE_VERSION}" gradle && \
    rm "${GRADLE_BINARY_FILE}" && \
    gradle -v

# Install dependencies via Gradle
ARG DEPS_DIR=${RUNNER_USER_HOME}/dependencies
ENV CLASSPATH ${DEPS_DIR}/*:${CLASSPATH}
COPY --chown=<%= chown %> images/<%= analyzer %>/build.gradle ${DEPS_DIR}/
RUN cd "${DEPS_DIR}" && \
    echo 'task deps(type: Copy) {' >> build.gradle && \
    echo '  from configurations.runtimeClasspath' >> build.gradle && \
    echo '  into "."' >> build.gradle && \
    echo '}' >> build.gradle && \
    gradle --no-build-cache --parallel --quiet deps && \
    rm build.gradle
