# Install the default version
COPY --chown=<%= chown %> images/<%= analyzer %>/package.json ${RUNNER_USER_HOME}/<%= analyzer %>_package.json
RUN cd "${RUNNER_USER_HOME}" && \
    mkdir <%= analyzer %> && \
    mv <%= analyzer %>_package.json <%= analyzer %>/package.json && \
    cd <%= analyzer %> && \
    npm config set ignore-scripts true && \
    npm config set progress false && \
    npm config set package-lock false && \
    npm install && \
    npm ls --depth 0 # Check required peer dependencies
ENV PATH ${RUNNER_USER_HOME}/<%= analyzer %>/node_modules/.bin:${PATH}
# See https://nodejs.org/api/cli.html#cli_node_path_path
ENV NODE_PATH ${RUNNER_USER_HOME}/<%= analyzer %>/node_modules:${NODE_PATH}
