module Runners
  class Analyzer
    attr_reader name: String
    attr_reader version: String

    def initialize: (name: String, version: String) -> void

    def valid?: () -> bool
    def as_json: () -> Hash[Symbol, String]
  end
end
