module Runners
  class Analyzers
    type analyzer = Hash[Symbol, untyped]
    type analyzer_id = Symbol | String

    def name: (analyzer_id) -> String

    def github: (analyzer_id) -> String

    def doc: (analyzer_id) -> String

    def deprecated?: (analyzer_id) -> bool

    private

    def content: () -> Hash[Symbol, analyzer]

    def analyzer: (analyzer_id) -> analyzer
  end
end
