class Runners::Analyzer
  attr_reader name: String
  attr_reader version: String

  def initialize: (name: String, version: String) -> untyped
  def valid?: () -> bool
  def as_json: () -> { name: String, version: String }
end
