module Runners
  class CLI
    include Tmpdir

    attr_reader stdout: ::IO
    attr_reader stderr: ::IO
    attr_reader guid: String
    attr_reader analyzer: Symbol
    attr_reader options: Options

    def initialize: (argv: Array[String], stdout: ::IO, stderr: ::IO, options_json: String) -> void

    def run: () -> void

    private

    def setup_bugsnag!: (Array[String]) -> void

    def setup_aws!: () -> void

    def with_working_dir: [X] () { (Pathname) -> X } -> X

    def processor_class: () -> singleton(Processor)

    def io: () -> Runners::IO

    def finish_message: (result) -> String

    def format_duration: (Float) -> String
  end
end
