module Runners
  class CLI
    include Tmpdir

    attr_reader stdout: ::IO
    attr_reader stderr: ::IO
    attr_reader guid: String
    attr_reader analyzer: String
    attr_reader options: Options

    def initialize: (argv: Array[String], stdout: ::IO, stderr: ::IO, options_json: String) -> void

    def run: () -> void

    private

    def setup_bugsnag!: (Array[String]) -> void

    def setup_aws!: () -> void

    def with_working_dir: [X] () { (Pathname) -> X } -> X

    def all_processor_classes: () -> Hash[String, Class]

    def processor_class: () -> Class

    def io: () -> Runners::IO

    def format_duration: (Float duration_in_sec) -> String
  end
end
