module Runners
  class Config
    class Error < UserError
      attr_reader raw_content: untyped

      def initialize: (String, String) -> void
    end

    class BrokenYAML < Error
    end

    class InvalidConfiguration < Error
    end

    CONFIG_FILE_NAME: String
    OLD_CONFIG_FILE_NAME: String

    def self.load_from_dir: (Pathname) -> instance

    attr_reader path: Pathname?
    attr_reader raw_content: String?
    attr_reader content: Hash[Symbol, untyped]

    def initialize: (Pathname?) -> void

    def raw_content!: () -> String

    def path_name: () -> String

    def path_exist?: () -> bool

    def ignore_patterns: () -> Array[String]

    def linter: (Symbol | String) -> Hash[Symbol, untyped]

    def linter?: (Symbol | String) -> bool

    private

    def parse_yaml: () -> untyped

    def check_schema: (untyped) -> Hash[Symbol, untyped]
  end
end
