module Runners
  class Config
    class Error < UserError
      attr_reader raw_content: untyped

      def initialize: (String, String) -> void
    end

    class BrokenYAML < Error
    end

    class InvalidConfiguration < Error
    end

    FILE_NAME: String
    FILE_NAME_OLD: String

    def self.load_from_dir: (Pathname) -> instance

    attr_reader path: Pathname?
    attr_reader raw_content: String?

    def initialize: (path: (Pathname | String)?, raw_content: String?) -> void

    def raw_content!: () -> String

    def content: () -> Hash[Symbol, untyped]

    alias validate content

    def path_name: () -> String

    def path_exist?: () -> bool

    def ignore_patterns: () -> Array[String]

    def linter: (Symbol | String) -> Hash[Symbol, untyped]

    def linter?: (Symbol | String) -> bool

    def check_unsupported_linters: (Array[String]) -> String

    def exclude_branch?: (String) -> bool

    private

    def parse_yaml: (String) -> untyped

    def check_schema: (untyped) -> Hash[Symbol, untyped]
  end
end
