module Runners
  module CPlusPlus : Processor
    CPP_SOURCES_GLOB: String
    CPP_HEADERS_GLOB: String

    def config_include_path: () -> Array[String]

    def cpp_file?: (Pathname) -> bool

    def install_apt_packages: () -> void

    private

    def find_paths_containing_headers: () -> Array[String]
  end
end
