module Runners
  class GitBlameInfo
    def self.parse: (String) -> Array[instance]

    attr_reader commit: String
    attr_reader original_line: Integer
    attr_reader final_line: Integer
    attr_reader line_hash: Integer

    def initialize: (commit: String, original_line: Integer, final_line: Integer, line_hash: Integer) -> void

    def as_json: () -> Hash[Symbol, String | Integer]
  end
end
