module Runners
  class Harness
    include Tmpdir

    class InvalidResult < SystemError
      attr_reader result: untyped

      def initialize: (result: untyped) -> void
    end

    attr_reader guid: String
    attr_reader processor_class: untyped
    attr_reader options: Options
    attr_reader working_dir: Pathname
    attr_reader trace_writer: TraceWriter
    attr_reader warnings: Array[String]
    attr_reader config: Config?

    @analyzer: Analyzer?

    def initialize: (guid: String,
                     processor_class: untyped,
                     options: Options,
                     working_dir: Pathname,
                     trace_writer: TraceWriter) -> void

    def run: () -> untyped

    private
    def ensure_result: () { () -> untyped } -> untyped
    def handle_error: (Exception) -> void
    def exclude_special_dirs: [X] () { () -> X } -> X
  end
end
