module Runners
  type io = IO::AwsS3

  class IO
    attr_reader ios: Array[::IO | io]

    def initialize: (*(::IO | io)) -> void

    def write: (*_ToS) -> void

    def flush: () -> void

    def flush!: () -> void
  end
end
