module Runners
  class Issue
    attr_reader path: Pathname
    attr_reader location: Location?
    attr_reader id: String?
    attr_reader message: String
    attr_reader links: Array[String]
    attr_reader object: Hash[Symbol, untyped]?
    attr_reader git_blame_info: GitBlameInfo?

    def initialize: (path: Pathname,
                     location: Location?,
                     id: String?,
                     message: String,
                     ?links: Array[String],
                     ?object: Hash[Symbol, untyped]?,
                     ?schema: StrongJSON::Type::Object[untyped]?) -> void

    def missing_id?: () -> bool

    def as_json: () -> Hash[Symbol, untyped]

    def add_git_blame_info: (Workspace) -> void
  end
end
