module Runners
  module Java : Processor
    class InvalidDependency < UserError
    end

    def install_jvm_deps: (?to: Pathname) -> void

    def pmd_version: () -> String

    private

    def fetch_deps_via_gradle!: () -> void

    def config_jvm_deps: () -> Array[String]

    def config_jvm_deps_old: () -> Array[String]

    def generate_jvm_deps_file: () -> void
  end
end
