module Runners
  class Location
    attr_reader start_line: Integer?
    attr_reader start_column: Integer?
    attr_reader end_line: Integer?
    attr_reader end_column: Integer?

    def initialize: (start_line: (Numeric | String)?,
                     ?start_column: (Numeric | String)?,
                     ?end_line: (Numeric | String)?,
                     ?end_column: (Numeric | String)?) -> void

    def as_json: () -> Hash[Symbol, Integer?]
  end
end
