module Runners
  module Nodejs : Processor
    type constraints = Hash[String, Constraint]

    class InvalidNodeVersion < SystemError
    end

    class InvalidNpmVersion < SystemError
    end

    class InvalidYarnVersion < SystemError
    end

    class ConstraintsNotSatisfied < UserError
    end

    class NpmInstallFailed < UserError
    end

    class YarnInstallFailed < UserError
    end

    INSTALL_OPTION_NONE: bool
    INSTALL_OPTION_ALL: bool
    INSTALL_OPTION_PRODUCTION: String
    INSTALL_OPTION_DEVELOPMENT: String

    type install_option = bool | String

    def nodejs_analyzer_local_command: () -> String

    def nodejs_analyzer_bin: () -> String

    def package_json_path: () -> Pathname

    def package_json: () -> Hash[Symbol, untyped]

    def package_lock_json_path: () -> Pathname

    def yarn_lock_path: () -> Pathname

    def install_nodejs_deps: (constraints: constraints, install_option: install_option) -> void

    private

    def nodejs_analyzer_locally_installed?: () -> bool

    def nodejs_analyzer_global_version: () -> String

    def nodejs_analyzer_local_version: () -> String

    def npm_install: (install_option) -> void

    def run_yarn: (String, *String) -> [String, String]

    def yarn_install: (install_option) -> void

    def list_installed_nodejs_deps: (?only: Array[String], ?chdir: Pathname | String | nil) -> Hash[String, String]

    def check_installed_nodejs_deps: (constraints) -> void
  end
end
