module Runners
  class Options
    class GitSource
      attr_reader head: String
      attr_reader base: String?
      attr_reader git_url: String
      attr_reader git_url_userinfo: String?
      attr_reader refspec: Array[String]

      def initialize: (Hash[Symbol, untyped]) -> void
    end

    attr_reader stdout: ::IO
    attr_reader stderr: ::IO
    attr_reader source: GitSource
    attr_reader ssh_key: String?
    attr_reader io: Runners::IO
    attr_reader secret_scan_urls: Array[String]

    def initialize: (String json, ::IO stdout, ::IO stderr) -> void

    private

    def parse_options: (String json) -> Hash[Symbol, untyped]
  end
end
