module Runners
  class Processor
    extend Forwardable

    include Tmpdir

    class CIConfigBroken < UserError
    end

    attr_reader guid: String
    attr_reader working_dir: Pathname
    attr_reader git_ssh_path: Pathname?
    attr_reader trace_writer: TraceWriter
    attr_reader warnings: Array[{ message: String, file: String? }]
    attr_reader config: Config
    attr_reader shell: Shell

    def self.register_config_schema: (name: Symbol, schema: StrongJSON::_Schema[untyped]) -> void

    class RemovedGoToolSchemaClass < StrongJSON
      def config: () -> StrongJSON::_Schema[untyped]
    end
    RemovedGoToolSchema: RemovedGoToolSchemaClass

    def initialize: (guid: String, working_dir: Pathname, config: Config, git_ssh_path: Pathname?, trace_writer: TraceWriter) -> void

    def current_dir: () -> Pathname
    def chdir: [X] (Pathname) { (Pathname) -> X } -> X
    def push_env_hash: [X] (Hash[String, String?]) { () -> X } -> X
    def env_hash: () -> Hash[String, String?]
    def capture3: (String, *String, **untyped) -> [String, String, Process::Status]
    def capture3!: (String, *String, **untyped) -> [String, String]
    def capture3_with_retry!: (String, *String, ?tries: Integer, ?sleep: ^(Integer) -> Numeric) -> [String, String]
    def capture3_trace: (String, *String, **untyped) -> [String, String, Process::Status]

    def relative_path: (String | Pathname, ?from: Pathname) -> Pathname

    def setup: () { () -> result } -> result

    def analyze: (Changes) -> result

    def analyzers: () -> Analyzers

    def analyzer_id: () -> String

    def analyzer_name: () -> String

    def analyzer_doc: () -> String

    def analyzer_github: () -> String

    def analyzer: () -> Analyzer

    def analyzer_bin: () -> String

    def analyzer_version: () -> String

    def extract_version_option: () -> String

    def extract_version!: ((String | Array[String]) command, ?(String | Array[String]) version_option, ?pattern: Regexp pattern) -> String

    def config_linter: () -> Hash[Symbol, untyped]

    def check_root_dir_exist: () -> Results::Failure?

    def in_root_dir: [X] () { (Pathname) -> X } -> X

    def root_dir: () -> Pathname

    def missing_config_file_result: (String) -> Results::Success

    def config_field_path: (*Symbol) -> String

    def delete_unchanged_files: (Changes, ?except: Array[String], ?only: Array[String]) -> void

    def add_warning: (String, ?file: String?) -> void

    def add_warning_if_deprecated_version: (minimum: String, ?file: String?, ?deadline: Time?) -> void

    def add_warning_if_deprecated_options: () -> void

    def add_warning_for_deprecated_option: (Symbol, to: Symbol) -> void

    def add_warning_for_deprecated_linter: (alternative: String, ref: String, ?deadline: Time?) -> void

    def directory_traversal_attack?: (Pathname) -> bool

    def show_runtime_versions: () -> void

    def report_file: () -> String

    def report_file_exist?: () -> bool

    def read_report_file: (?String) -> String

    class InvalidXML < SystemError
    end

    def read_xml: (String) -> REXML::Element

    def read_report_xml: (?String) -> REXML::Element

    def read_report_json: [X] (?String) { () -> X } -> (X | untyped)
                        | (?String) -> untyped

    def comma_separated_list: (String | Array[String] | nil) -> String?
  end
end
