module Runners
  module Ruby : Processor
    type constraints = Hash[String, Array[String]]

    class InstallGemsFailure < UserError
    end

    def install_gems: [X] (Array[GemInstaller::Spec], constraints: constraints, ?optionals: Array[GemInstaller::Spec]) { (Hash[String, String]) -> X } -> X

    def ruby_analyzer_command: (*String) -> Command

    def installed_gem_versions: (Array[String], ?exception: bool) -> Hash[String, Array[String]]

    def default_gem_specs: (String, *String) -> Array[GemInstaller::Spec]

    private

    def default_specs: (Array[GemInstaller::Spec], constraints, LockfileLoader::Lockfile) -> Array[GemInstaller::Spec]

    def optional_specs: (Array[GemInstaller::Spec], LockfileLoader::Lockfile) -> Array[GemInstaller::Spec]

    def user_specs: (Array[GemInstaller::Spec] specs, LockfileLoader::Lockfile) -> Array[GemInstaller::Spec]
  end
end
