module Runners
  class Workspace
    include Tmpdir

    def self.prepare: (options: Options, working_dir: Pathname, trace_writer: TraceWriter) -> Workspace

    attr_reader options: Options
    attr_reader working_dir: Pathname
    attr_reader trace_writer: TraceWriter
    attr_reader shell: Shell

    def initialize: (options: Options, working_dir: Pathname, trace_writer: TraceWriter) -> void

    def open: [X] () { (Pathname?, Changes) -> X } -> X

    def range_git_blame_info: (String, Integer, Integer, ?trace: bool) -> Array[GitBlameInfo]

    def prepare_head_source: () -> void

    def patches: () -> GitDiffParser::Patches

    private

    def prepare_ssh: [X] () { (Pathname?) -> X } -> X
  end
end
