module Runners
  class Ruby::GemInstaller
    class Source
      DEFAULT: String

      def self.default: () -> instance

      def self.create: (gems_item) -> instance

      def rubygems?: () -> bool

      def git?: () -> bool

      def default?: () -> bool

      class Rubygems < Source
        attr_reader source: String

        def initialize: (String) -> void
      end

      class Git < Source
        attr_reader repo: String
        attr_reader ref: String?
        attr_reader branch: String?
        attr_reader tag: String?

        def initialize: (git_source) -> void
      end
    end
  end
end
