module Runners
  class Ruby::GemInstaller
    class Source
      DEFAULT: untyped

      def self.default: () -> untyped

      def self.rubygems: (untyped source) -> untyped

      def self.git: (untyped repo, **untyped options) -> untyped

      def self.create: (untyped gems_item) -> untyped

      def rubygems?: () -> ::FalseClass

      def git?: () -> ::FalseClass

      def default?: () -> ::FalseClass

      # @see https://bundler.io/man/gemfile.5.html#SOURCE
      class Rubygems < Source
        attr_reader source: untyped

        def initialize: (untyped source) -> untyped

        def rubygems?: () -> ::TrueClass

        def default?: () -> untyped

        def ==: (untyped other) -> untyped

        def hash: () -> untyped

        def to_s: () -> ::String
      end

      # @see https://bundler.io/man/gemfile.5.html#GIT
      class Git < Source
        attr_reader repo: untyped

        attr_reader ref: untyped

        attr_reader branch: untyped

        attr_reader tag: untyped

        def initialize: (untyped repo, ?ref: untyped? ref, ?branch: untyped? branch, ?tag: untyped? tag) -> untyped

        def git?: () -> ::TrueClass

        def ==: (untyped other) -> untyped

        def hash: () -> untyped

        def to_s: () -> untyped
      end
    end
  end
end
