module Runners
  class Ruby::GemInstaller
    class Source
      def self.default: () -> instance

      attr_reader uri: String?
      attr_reader repo: String?
      attr_reader ref: String?
      attr_reader branch: String?
      attr_reader tag: String?

      def initialize: (?uri: String?, ?git: Ruby::git_source?) -> void

      def git?: () -> bool

      def default?: () -> bool
    end
  end
end
