module Runners
  module Ruby
    class GemInstaller
      class Spec
        attr_reader name: String
        attr_reader version: Array[String]
        attr_reader source: Source

        def initialize: (name: String, version: Array[String], ?source: Source) -> void

        def override_by_lockfile: (LockfileLoader::Lockfile) -> Spec

        def self.from_gems: (Array[gems_item | String]) -> Array[Spec]

        def self.merge: (Array[Spec], Array[Spec]) -> Array[Spec]
      end
    end
  end
end
