module Runners
  module Ruby
    class GemInstaller
      class Spec
        attr_reader name: String
        attr_reader requirement: Gem::Requirement
        attr_reader source: Source

        def initialize: (String, ?requirement: (Array[String | Gem::Version] | Gem::Requirement), ?source: Source) -> void

        def override_by_lockfile: (LockfileLoader::Lockfile) -> instance
      end
    end
  end
end
