FROM sider/devon_rex_ruby:2.2.2

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.ruby.erb' %>

COPY images/haml_lint/default_rubocop.yml $RUNNER_USER_HOME/

<%= render_erb 'images/Dockerfile.end.erb' %>
