FROM sider/devon_rex_ruby:2.1.0

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

RUN gem install scss_lint -v 0.57.1
COPY images/scss_lint/scss-lint.default.yml $RUNNER_USER_HOME/.scss-lint.yml

ENTRYPOINT ["node_harness", "--analyzer=scss_lint"]
