FROM sider/devon_rex_ruby:2.3.1

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.ruby.erb' %>

COPY images/scss_lint/scss-lint.default.yml $RUNNER_USER_HOME/.scss-lint.yml

<%= render_erb 'images/Dockerfile.end.erb' %>
