module Runners
  module Ruby
    class LockfileLoader
      include Tmpdir

      class InvalidGemfileLock < InstallGemsFailure
      end

      attr_reader root_dir: Pathname
      attr_reader shell: Shell

      def initialize: (root_dir: Pathname, shell: Shell) -> void

      def ensure_lockfile: [X] () { (Lockfile) -> X } -> X

      private

      def gemfile_path: () -> Pathname

      def gemfile_lock_path: () -> Pathname

      def generate_lockfile: (Pathname) -> String?
    end
  end
end
