#!/usr/bin/env ruby

# node_harness_smoke lib/entrypoint.rb test/smoke/expectations.rb

require "pathname"

$LOAD_PATH << Pathname(__dir__).parent + "lib"

require "node_harness"
require "node_harness/testing/smoke"

NodeHarness::Testing::Smoke.new(ARGV).run
