#!ruby
require 'thor'
require 'node_harness'

class CLI < Thor
  include Thor::Actions

  desc 'generate runner_name', 'generate runner'
  def generate(name)
    empty_directory name
    directory 'lib', "#{name}/lib"
    directory 'test', "#{name}/test"
    copy_file 'Gemfile', "#{name}/Gemfile"
    template 'gems.yaml.erb', "#{name}/gems.yaml", { version: NodeHarness::VERSION }
    template 'Rakefile.erb', "#{name}/Rakefile", { runner_name: name }
    copy_file 'Dockerfile', "#{name}/Dockerfile"
    copy_file '.gitignore', "#{name}/.gitignore"
    copy_file '.dockerignore', "#{name}/.dockerignore"
    copy_file '.travis.yml', "#{name}/.travis.yml"
    copy_file '.ruby-version', "#{name}/.ruby-version"
  end
  desc 'g runner_name', 'alias for generate'
  alias_method :g, :generate
end

template_path = File.expand_path('../../templates', __FILE__)
CLI.source_root(template_path)
CLI.start(ARGV)
