#!/usr/bin/env ruby

$LOAD_PATH.prepend File.join(__dir__.to_s, "..", "lib")

require "runners"
require "runners/cli"

Signal.trap('SIGTERM') do
  Bugsnag.notify(Runners::TimeoutError.new)
  exit Runners::Exitstatus::SIGTERM
end

Signal.trap('SIGUSR2') do
  Bugsnag.notify(Runners::TimeoutError.new)
end

begin
  Runners::CLI.new(
    argv: ARGV.dup,
    stdout: STDOUT,
    stderr: STDERR,
    options_json: ENV.delete("RUNNERS_OPTIONS"),
  ).run
rescue => exn
  Bugsnag.notify(exn)
  raise
end
