FROM hadolint/hadolint:v1.18.2-debian as hadolint

FROM sider/devon_rex_base:master

COPY --chown=<%= chown %> --from=hadolint /bin/hadolint ${RUNNER_USER_HOME}/bin/

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
