FROM hadolint/hadolint:v1.17.6-debian as hadolint

FROM sider/devon_rex_base:2.19.0

COPY --chown=<%= chown %> --from=hadolint /bin/hadolint ${RUNNER_USER_HOME}/bin/

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
