FROM sider/devon_rex_go:2.10.0

ARG LINT_TOOL_VERSION="2.0.11"

USER root
RUN curl -sSL --compressed https://github.com/alecthomas/gometalinter/releases/download/v${LINT_TOOL_VERSION}/gometalinter-${LINT_TOOL_VERSION}-linux-amd64.tar.gz | \
    tar -xzC . && \
    cd gometalinter-${LINT_TOOL_VERSION}-linux-amd64/ && \
    rm COPYING README.md && \
    mv * /usr/local/bin/ && \
    cd .. && \
    rm -r gometalinter-${LINT_TOOL_VERSION}-linux-amd64/
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.base.erb' %>

COPY --chown=<%= ENV.fetch("RUNNER_CHOWN") %> images/gometalinter/gometalinter.json ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
