FROM sider/devon_rex_php:2.0.3

<%= ERB.new(File.read('images/Dockerfile.base.erb')).result %>

COPY images/phpmd/composer.json images/phpmd/composer.lock $COMPOSER_HOME/
COPY images/phpmd/sider_config.xml $RUNNER_USER_HOME/
RUN composer global install

ENTRYPOINT ["node_harness", "--analyzer=phpmd"]
