FROM sider/devon_rex_php:master

<%= render_erb 'images/Dockerfile.php.erb' %>
<%= render_erb 'images/Dockerfile.base.erb' %>

COPY images/phpmd/sider_config.xml ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
