FROM sider/devon_rex_php:2.6.0

<%= render_erb 'images/Dockerfile.php.erb' %>
<%= render_erb 'images/Dockerfile.base.erb' %>

COPY --chown=${RUNNER_USER}:${RUNNER_GROUP} images/phpmd/sider_config.xml ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
