# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
# PLEASE UPDATE Dockerfile.erb INSTEAD OF THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FROM sider/devon_rex_php:2.4.0

ARG RUNNERS_DIR=${RUNNER_USER_HOME}/runners
COPY Gemfile* Rakefile ${RUNNERS_DIR}/
COPY bin ${RUNNERS_DIR}/bin
COPY lib ${RUNNERS_DIR}/lib
USER root
RUN chown -R ${RUNNER_USER}: ${RUNNERS_DIR}
USER $RUNNER_USER

RUN cd ${RUNNERS_DIR} && \
    bundle config --global jobs 4 && \
    bundle config --global retry 3 && \
    bundle config && \
    bundle install --without='development test'
ENV PATH ${RUNNERS_DIR}/bin:${PATH}

ENV PHPCS3_VERSION="3.4.2" \
    CAKEPHP_CS3_VERSION="3.1.1" \
    SYMFONY_CS3_VERSION="3.4.1" \
    WORDPRESS_CS3_VERSION="2.0.0"

# Installation requires root permission
USER root

# Install PHP_CodeSniffer 3.x from GitHub releases (It is good to use pear, But it does not support multiple versions)
RUN wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/${PHPCS3_VERSION}/phpcs.phar \
  && mv phpcs.phar phpcs3 \
  && chmod +x phpcs3 \
  && mv phpcs3 /usr/bin \
  && mkdir -p /usr/share/php/PHP/CodeSniffer3/Standards

# Install CakePHP Coding Standards for PHPCS3
RUN wget https://github.com/cakephp/cakephp-codesniffer/archive/${CAKEPHP_CS3_VERSION}.zip \
  && unzip ${CAKEPHP_CS3_VERSION}.zip \
  && mv cakephp-codesniffer-${CAKEPHP_CS3_VERSION}/CakePHP /usr/share/php/PHP/CodeSniffer3/Standards \
  && rm -rf ${CAKEPHP_CS3_VERSION}.zip cakephp-codesniffer-${CAKEPHP_CS3_VERSION}/

# Install Symfony Coding Standards for PHPCS3
RUN wget https://github.com/djoos/Symfony-coding-standard/archive/${SYMFONY_CS3_VERSION}.zip \
  && unzip ${SYMFONY_CS3_VERSION}.zip \
  && mv Symfony-coding-standard-${SYMFONY_CS3_VERSION}/Symfony /usr/share/php/PHP/CodeSniffer3/Standards \
  && rm -rf ${SYMFONY_CS3_VERSION}.zip Symfony2-coding-standard-${SYMFONY_CS3_VERSION}/

# Install WordPress Coding Standards for PHPCS3
RUN wget https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/${WORDPRESS_CS3_VERSION}.zip \
  && unzip ${WORDPRESS_CS3_VERSION}.zip \
  && mv WordPress-Coding-Standards-${WORDPRESS_CS3_VERSION} /usr/share/php/PHP/CodeSniffer3/Standards/wpcs \
  && rm ${WORDPRESS_CS3_VERSION}.zip

# Set install paths
RUN phpcs3 --config-set installed_paths /usr/share/php/PHP/CodeSniffer3/Standards,/usr/share/php/PHP/CodeSniffer3/Standards/wpcs

USER $RUNNER_USER

USER root
RUN chown -R ${RUNNER_USER}: ${RUNNER_USER_HOME}
USER $RUNNER_USER

ENTRYPOINT ["runners", "--analyzer=code_sniffer"]
