FROM sider/devon_rex_swift:2.12.0

ARG SWIFTLINT_VERSION=0.38.2

# Build SwiftLint
USER root
RUN SWIFTLINT_BUILD_DIR=/tmp/swiftlint_build && \
    git clone --branch ${SWIFTLINT_VERSION} --single-branch https://github.com/realm/SwiftLint.git ${SWIFTLINT_BUILD_DIR} && \
    cd ${SWIFTLINT_BUILD_DIR} && \
    make install && \
    swiftlint version && \
    rm -rf ${SWIFTLINT_BUILD_DIR}
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
