FROM sider/devon_rex_swift:master

ARG SWIFTLINT_VERSION=0.39.2

ENV PATH ${RUNNER_USER_HOME}/bin:${PATH}

# Build SwiftLint
RUN cd /tmp && \
    curl -sSL --compressed https://github.com/realm/SwiftLint/archive/${SWIFTLINT_VERSION}.tar.gz | tar -xz && \
    cd SwiftLint-${SWIFTLINT_VERSION} && \
    make install BINARIES_FOLDER=${RUNNER_USER_HOME}/bin && \
    cd .. && \
    rm -rf SwiftLint-${SWIFTLINT_VERSION} && \
    swiftlint version

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
