FROM sider/devon_rex_base:master

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends file && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH ${RUNNER_USER_HOME}/bin:${PATH}
COPY --chown=<%= chown %> --from=koalaman/shellcheck:v0.7.1 /bin/shellcheck ${RUNNER_USER_HOME}/bin/

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
