// Sider's recommended ruleset is based on eslint:recommended,
// and following rules are additionally enabled/disabled.
// See https://eslint.org/docs/rules/ for more details.
// And, we generated the ruleset using ESLint 7.17, on 2021-04-05.
module.exports = {
  "parserOptions": {"ecmaVersion": 2015},
  "extends": ["eslint:recommended"],
  "rules": {
    // Disabled [Variables] (Overriding rules included in `eslint:recommended`)
    "no-undef": "off",
    "no-unused-vars": "off",

    // Enabled [Possible Errors]
    "no-await-in-loop": "warn",
    "no-loss-of-precision": "warn",
    "no-promise-executor-return": "warn",
    "no-template-curly-in-string": "warn",
    "no-unreachable-loop": "warn",
    "no-unsafe-optional-chaining": "warn",
    "no-useless-backreference": "warn",
    "require-atomic-updates": "warn",

    // Enabled [Best Practices]
    "accessor-pairs": "warn",
    "array-callback-return": "warn",
    "block-scoped-var": "warn",
    "class-methods-use-this": "warn",
    "default-case-last": "warn",
    "default-param-last": "warn",
    "eqeqeq": ["warn", "smart"],
    "grouped-accessor-pairs": "warn",
    "guard-for-in": "warn",
    "max-classes-per-file": "warn",
    "no-alert": "warn",
    "no-caller": "warn",
    "no-constructor-return": "warn",
    "no-div-regex": "warn",
    "no-empty-function": "warn",
    "no-eval": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-extra-label": "warn",
    "no-implied-eval": "warn",
    "no-invalid-this": "warn",
    "no-iterator": "warn",
    "no-labels": "warn",
    "no-lone-blocks": "warn",
    "no-loop-func": "warn",
    "no-multi-str": "warn",
    "no-new": "warn",
    "no-new-func": "warn",
    "no-new-wrappers": "warn",
    "no-nonoctal-decimal-escape": "warn",
    "no-octal-escape": "warn",
    "no-param-reassign": "warn",
    "no-proto": "warn",
    "no-restricted-properties": "warn",
    "no-return-assign": "warn",
    "no-return-await": "warn",
    "no-script-url": "warn",
    "no-self-compare": "warn",
    "no-sequences": "warn",
    "no-throw-literal": "warn",
    "no-unmodified-loop-condition": "warn",
    "no-unused-expressions": "warn",
    "no-useless-call": "warn",
    "no-useless-concat": "warn",
    "no-useless-return": "warn",
    "no-warning-comments": "warn",
    "prefer-promise-reject-errors": "warn",
    "prefer-regex-literals": "warn",
    "radix": "warn",
    "require-await": "warn",
    "vars-on-top": "warn",

    // Enabled [Variables]
    "no-label-var": "warn",
    "no-restricted-globals": "warn",
    "no-undef-init": "warn",

    // Enabled [Stylistic Issues]
    "func-name-matching": "warn",
    "id-denylist": "warn",
    "id-match": "warn",
    "no-array-constructor": "warn",
    "no-lonely-if": "warn",
    "no-multiple-empty-lines": "warn",
    "no-new-object": "warn",
    "no-restricted-syntax": "warn",
    "no-unneeded-ternary": "warn",
    "no-whitespace-before-property": "warn",
    "prefer-exponentiation-operator": "warn",
    "prefer-object-spread": "warn",

    // Enabled [ECMAScript 6]
    "arrow-parens": "warn",
    "arrow-spacing": "warn",
    "generator-star-spacing": "warn",
    "no-confusing-arrow": "warn",
    "no-duplicate-imports": "warn",
    "no-restricted-exports": "warn",
    "no-restricted-imports": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-constructor": "warn",
    "no-useless-rename": "warn",
    "prefer-const": "warn",
    "prefer-numeric-literals": "warn",
    "symbol-description": "warn"
  }
}
